### ISSUE TITLE
The cited resource doesn't work on Chrome.

### ISSUE THREAD

**Issue by andrewkjankowski** [learn-co-curriculum/code-along-working-with-apis#15]
http://dev.socrata.com/foundry/#/data.cityofnewyork.us/uvks-tn5n

Lots of JS errors in the console. Probably something on the Socrata side, but figured I'd raise it here so you're aware.

It works just fine in Firefox.

**Comment by drakeltheryuujin** [comment]
Thank you for spotting this issue and providing feedback.
We have updated the materials and believe your issue to have been resolved.
If you do not believe that this issue has been addressed, please re-open this issue. 💙
