### ISSUE TITLE
use http instead of https

### ISSUE THREAD

**Issue by loganhasson** [learn-co-curriculum/code-along-working-with-apis#5]
seems like there's an issue connecting to the api using https

**Comment by AnnJohn** [comment]
Assigned to @SophieDeBenedetto 

Can you look into today?

**Comment by SophieDeBenedetto** [comment]
@loganhasson it's working for me with either http or https. is this an issue you had or a student?

**Comment by loganhasson** [comment]
@SophieDeBenedetto a student had the issue originally, but I get it as well

**Comment by SophieDeBenedetto** [comment]
@loganhasson does it work for you if you use http?

**Comment by loganhasson** [comment]
@SophieDeBenedetto yep

**Comment by SophieDeBenedetto** [comment]
seems like @sammarcus fixed this. i'm closing.
